### ISSUE TITLE
No way to pass parameters to ViewModel when providing it to the Fragment (using Koin)

### ISSUE THREAD

**Issue by Benjiko99** [rainbowcake/rainbowcake#10]
Koin lets me define additional parameters to pass to the constructor of my ViewModels when they're being injected. RainbowCake doesn't support this.

```kotlin
val uiModule = module {
    viewModel { (detailId: String) -> DetailViewModel(id, get()) }
}
```

```kotlin
class DetailFragment : RainbowCakeFragment<DetailViewState, DetailViewModel>() {

    // No way to pass parameters to getViewModelFromFactory()
    override fun provideViewModel() = getViewModelFromFactory()
}
```

Since I'm forced to implement `provideViewModel()` which is called from `RainbowCakeFragment#onCreate()`, I'm left with this ugly workaround to pass parameters to my ViewModel:

### Workaround: member variable initialized before `super.onCreate()`
```kotlin
class DetailFragment : RainbowCakeFragment<DetailViewState, DetailViewModel>() {

    private lateinit var detailId: String

    override fun provideViewModel(): DetailViewModel {
        return getViewModel { parametersOf(detailId) }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        if (savedInstanceState == null) {
            DetailFragmentArgs.fromBundle(requireArguments()).let { args ->
                detailId = args.detailId
            }
        }

        super.onCreate(savedInstanceState)

        viewModel.loadData()
    }
}
```

**Comment by Benjiko99** [comment]
I propose that the contents of  `RainbowCakeFragment#onCreate()` be pulled out into a method that the developer will be responsible for calling in his `onCreate()` implementation. There are many cases when I might need to be fully in control over when the `ViewModel` Is created, the current approach is too limiting.

Yes, you'll lose the nice syntax of just overring `provideViewModel()`, and add the boilerplate of requiring to have an `onCreate()` method, but you're currently assuming too much about my initialization procedures and it gets in the way.

**Comment by zsmb13** [comment]
The workaround actually seems like a pretty clean implementation to me, the only real practical difference between that and the proposed solution in the PR is the way that you fetch the value that you then pass in to the Koin ViewModel fetch.

This is exactly why RainbowCake gives you the ability to have arbitrary implementation in `provideViewModel`, if you don't like what the `getViewModelFromFactory` methods give you (which are there to support the simplest use cases). I believe your workaround here is the indented usage.

Regarding the PR itself: please see my comment there.

**Comment by Benjiko99** [comment]
Fine, let's close this issue so we don't have to introduce a breaking change. But since this is an architectural project, the discussion is probably still good to have, at least for fun.

I think the code is screaming at us that it wants the initialization of the ViewModel to happen within `onCreate()`. I have to split my initialization into 3 different places within the Fragment and then have lingering member variables that do nothing, this is clearly a code smell. 

You were able to extract it into `provideViewModel()` because you only accidentally happened to be in a context of not needing additional parameterization, which made it look like there could never be any late dependencies (e.g. fragment arguments). 

There can be late dependencies. The current approach was naively assuming that those wouldn't exist, and should probably be changed to better reflect the reality of initializing ViewModels within Android.

E.g. it should look like this 
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    getViewModelFromFactory().initWithRainbowCake()
}
```

And also support this
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    if (savedInstanceState == null) {
        DetailFragmentArgs.fromBundle(requireArguments()).let { args ->
            getViewModel { parametersOf(args.detailId) }.initWithRainbowCake()
        }
    }

    viewModel.loadData()
}
```

**Comment by Benjiko99** [comment]
I've found a solution that I like, don't desire the changes anymore.

```kotlin
override fun provideViewModel(): DetailViewModel {
    DetailFragmentArgs.fromBundle(requireArguments()).let { args ->
        return getViewModel { parametersOf(detailId) }
    }
}
```
