### ISSUE TITLE
Toothpick support

### ISSUE THREAD

**Issue by dobrowins** [rainbowcake/rainbowcake#14]
Has anyone tried to use this framework with DI from Toothpick?
It shouldn't matter as long as you provide factory for viewmodels though.

If no one has — what can I do to make framework work with it?

**Comment by dobrowins** [comment]
Ok, took a look at koin module. Going to work on it.

**Comment by zsmb13** [comment]
Yup, you should be integrate your own DI solutions to the framework, just like the Dagger and the Koin modules are currently integrated. Good luck 😄
