### ISSUE TITLE
How to get result from fragment?

### ISSUE THREAD

**Issue by amirzeinaly** [rainbowcake/rainbowcake#15]
Hi I want to know do you have any solution for get result from 2nd fragment when came back to 1st fragment like onActivityResult()

thanks in advanced

**Comment by Benjiko99** [comment]
https://developer.android.com/training/basics/fragments/pass-data-between

**Comment by zsmb13** [comment]
RainbowCake doesn't offer dedicated support for this. Therefore, the link in the previous comment is pretty much the correct answer to the question.
