### ISSUE TITLE
Add databinding support

### ISSUE THREAD

**Issue by jmpaya** [rainbowcake/rainbowcake#20]
Hi Márton,

First of all congratulations for your library, it is just a masterpiece that can save hundreds of hours to the community.

I'd like to suggest you to support in some way databinding on `RainbowCakeFragment`. I'm using your library on some projects and  I think It could be interesting to support this pattern.

I've solved it doing that on my project:

    class MyFragment : RainbowCakeFragment<MyViewState, MyViewModel>() {

        override fun getViewResource() = R.layout.my_fragment

        override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
            super.onCreateView(inflater, container, savedInstanceState) // I'm forced to call super
            binding = MyFragmentListBinding.inflate(inflater, container, false)
            return binding.root
        }

        override fun render(viewState: MyViewState) {
            TransitionManager.beginDelayedTransition(listFragmentRoot)
            binding.viewState = viewState
        }
    }

As you can see it simplifies a lot the code on the Fragment side, moving the logic to the XML file. Maybe you can find a better way of allowing this on next versions of the library without having to override `getViewResource()` method.

**Comment by zsmb13** [comment]
This is a good point, both ViewBinding and data binding would be interesting things to support. Have to figure out how to do this without breaking the existing APIs too much, or making the XML resource based solution too manual to use.

**Comment by jmpaya** [comment]
Awesome! 👍

**Comment by zsmb13** [comment]
Made this nicer in [1.2.0](https://github.com/rainbowcake/rainbowcake/releases/tag/1.2.0-RELEASE)

**Comment by jmpaya** [comment]
That's amazing @zsmb13! A million thanks for the update! :top:

**Comment by jmpaya** [comment]
It's working fine on 1.2.0. Closing the issue. 😄
