### ISSUE TITLE
How to stop reload data on navigator.pop() action?

### ISSUE THREAD

**Issue by amirzeinaly** [rainbowcake/rainbowcake#27]
Hi I have simple question
I Add fragment A -> navigator.add(A())
then I Add Fragment B ->  navigator.add(B())
after that when I came back to fragment A(navigator.pop()) 
Fragment A reloaded

What can I do to stop reload Fragment?

thanks

**Comment by zsmb13** [comment]
The documentation covers this in [ViewModel init](https://rainbowcake.dev/features/viewmodel-init/). The TLDR is, it's up to you to figure out when you want to reload state, by calling into the ViewModel from the Fragment as needed for your use case.
