### ISSUE TITLE
Provide guidance on modifying the library within a project

### ISSUE THREAD

**Issue by Benjiko99** [rainbowcake/rainbowcake#37]
I wanted to add the library as a git submodule into my project so that it becomes a part of my codebase and I can make any modifications to it easily and not have to distribute them through maven or anything.

I couldn't get it to work. I then also tried just regularly forking the repo and building it though mavenLocal but that also didn't work, as you have custom scripts in your build.gradle that trigger on build and try to sign the build and publish it to your maven reposities. Honestly I don't have any experience with this and it would nice if you could provide some help.

**Comment by zsmb13** [comment]
This question is out of scope for the library, there's nothing exotic in the project in this regard. If you don't want to sign artifacts, you can simply remove that part of the Gradle configuration.
