### ISSUE TITLE
Support both Hilt and Dagger2

### ISSUE THREAD

**Issue by mochadwi** [rainbowcake/rainbowcake#6]
Great jobs for what you guys have done for this project. It solves most of our plan to creating template and start writing clean architecture, simple mapper, MVI, Flow and many more.

Now that Hilt release (still alpha). Any plans working on to support Hilt as well? (not replacing Dagger2)

**Comment by zsmb13** [comment]
While there's no public roadmap, Hilt support is definitely something RainbowCake is likely to support in the future. As described on the [Dependency Injection](https://rainbowcake.dev/features/dependency-injection/) page of the docs, you should be able to integrate with Hilt already yourself, but some additional support for it might ship later.
