### ISSUE TITLE
Supports for API Level 16

### ISSUE THREAD

**Issue by mochadwi** [rainbowcake/rainbowcake#8]
Currently the rainbow-cake library has minimum sdk targeted to 19, is this possible to have a support for api level 16? @zsmb13 

<img width="552" alt="Screen Shot 2020-07-15 at 3 28 18 PM" src="https://user-images.githubusercontent.com/7057959/87522559-fa59ff80-c6af-11ea-8916-6b9dbf05dc66.png">

**Comment by zsmb13** [comment]
Thanks for the interest. RainbowCake will not be supporting API levels below 19, the minsdk version will only move higher up in the future (though I don't expect the need to move it higher than 19 anytime soon).
