### ISSUE TITLE
Do you support Rx instead coroutine?

### ISSUE THREAD

**Issue by TieuNhi95** [rainbowcake/rainbowcake#9]

**Comment by zsmb13** [comment]
You can ignore RainbowCake's built-in support for coroutines and use Rx instead from the ViewModel to the Data source layers quite easily, if you have a preference for that.

**Comment by TieuNhi95** [comment]
@zsmb13 if i use Rx, Presenter need reference of viewState to update, so, this paradigm not right.
[https://d33wubrfki0l68.cloudfront.net/5c87ced651e328f33727b33bbe9a871e482350a2/63186/images/arch_overview.png](url)

**Comment by zsmb13** [comment]
I'm not sure what the issue is with Rx, could you put this in terms of code? You can use the `viewState` property to read the current state or to set a new one. I don't see how this is incompatible with Rx.
